source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "9.0"

use_frameworks!

pod "AFNetworking"

pod "SDWebImage"

pod "SnapKit"

pod "SVProgressHUD"

pod "MJRefresh"

pod "HYLabel"

target "Swift_Sina" do

end
